# Generated by Django 4.0 on 2021-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
