# Generated by Django 4.0 on 2021-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_image/%Y/%m/%d'),
        ),
    ]
