# Generated by Django 4.0 on 2021-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Sometext', max_length=1000),
            preserve_default=False,
        ),
    ]
