# Generated by Django 4.0 on 2021-12-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_siteuser_followers_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='follower',
        ),
    ]
