# Generated by Django 4.0 on 2021-12-26 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_owner_alter_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
