# Generated by Django 4.0 on 2021-12-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_siteuser_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='changed_at',
            new_name='edited_at',
        ),
    ]
