# Generated by Django 4.0 on 2022-01-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_changed_at_post_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='followers',
        ),
    ]
