# Generated by Django 4.0 on 2022-01-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
